#!/usr/bin/env bash
# Generate the Kiro CLI versions of the harness commands, so both tools read the same instructions.
#
#   .claude/commands/<name>.md  ->  .kiro/prompts/<name>.md        (Kiro CLI: @<name> <arguments>)
#   attach/commands/<name>.md   ->  attach/kiro-prompts/<name>.md  (copied into a given repo by attach.sh)
#
# Why prompts and not steering: Kiro CLI loads EVERY file in .kiro/steering/ into every session
# (inclusion modes are IDE-only), so commands must live in .kiro/prompts/ and be called with @name.
# Only the always-on rules (.kiro/steering/harness.md) belong in steering.
# Edit the .claude/commands or attach/commands version, then re-run ./kiro-sync.sh.
set -euo pipefail
cd "$(dirname "$0")"

to_kiro() {   # /scaffold -> @scaffold (twice, so back-to-back references both convert)
  sed -E 's@(^|[[:space:]`(])/(scaffold|fr-tests|nfr-tests|pattern|audit|hld|hint|onboard|next)([^a-zA-Z0-9-]|$)@\1\@\2\3@g' \
    | sed -E 's@(^|[[:space:]`(])/(scaffold|fr-tests|nfr-tests|pattern|audit|hld|hint|onboard|next)([^a-zA-Z0-9-]|$)@\1\@\2\3@g'
}

convert() {   # $1 = source dir, $2 = output dir, $3 = path prefix shown in the fallback hint
  local src_dir="$1" out_dir="$2" prefix="$3" src name desc hint count=0
  rm -rf "$out_dir"
  mkdir -p "$out_dir"
  for src in "$src_dir"/*.md; do
    name="$(basename "$src" .md)"
    desc="$(sed -n 's/^description:[[:space:]]*//p' "$src" | head -1 | to_kiro)"
    hint="$(sed -n 's/^argument-hint:[[:space:]]*//p' "$src" | head -1)"
    {
      echo "<!-- Kiro CLI saved prompt. Generated by kiro-sync.sh from $src: edit that file, then run ./kiro-sync.sh -->"
      echo "# @$name: $desc"
      echo
      echo "Usage: \`@$name $hint\`"
      echo "(If the arguments don't come through, use \`@$prefix/$name.md <arguments>\` instead.)"
      echo
      echo "Arguments: \$ARGUMENTS"
      echo "(If the line above shows a placeholder instead of real arguments, my arguments are the rest of my message.)"
      echo
      # body = everything after the front matter; $ARGUMENTS -> "the arguments above"; /cmd -> @cmd
      awk 'n >= 2 { print; next } /^---$/ { n++ }' "$src" \
        | sed -e 's/\$ARGUMENTS/the arguments above/g' \
        | to_kiro
    } > "$out_dir/$name.md"
    count=$((count + 1))
  done
  echo "  $count prompts: $src_dir -> $out_dir"
}

echo "Kiro CLI prompts generated:"
convert ".claude/commands" ".kiro/prompts" ".kiro/prompts"
convert "attach/commands" "attach/kiro-prompts" ".kiro/prompts"
